### ISSUE TITLE
Raw serializer not implemented by jackson

### ISSUE THREAD

**Issue by danjee** [l0rdn1kk0n/wicket-jquery-selectors#17]
I want to serialize some javascript function as a raw value but it leads me to some error.
The stacktrace is this:

```java
java.lang.UnsupportedOperationException: Called operation not supported for TokenBuffer
     at com.fasterxml.jackson.databind.util.TokenBuffer._reportUnsupportedOperation(TokenBuffer.java:1066)
     at com.fasterxml.jackson.databind.util.TokenBuffer.writeRawValue(TokenBuffer.java:709)
     at de.agilecoders.wicket.jquery.util.serializer.RawSerializer.serialize(RawSerializer.java:18)
     at de.agilecoders.wicket.jquery.util.serializer.RawSerializer.serialize(RawSerializer.java:15)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:491)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:412)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:27)
     at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
     at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1902)
```

It looks like the RawSerializer calls a not implemented method from `TokenBuffer` class. Is there a possiblity to choose another implementation for the `JsonGenerator` ?

My code is this:

```java
RawValue scoreFunction = new RawValue("function(search) { var score = this.getScoreFunction(search); return function(item) { return score(item) * (1 + Math.min(item.watchers / 100, 1)); };");
		selectizeConfig.withScore(scoreFunction);
```

**Comment by martin-g** [comment]
This has been fixed in Jackson 2.6+

**Comment by danjee** [comment]
I will force the new library then in my pom.xml. I forgot to mention I am using the latest wicket-jquery-selectors artifact. Many thanks

**Comment by martin-g** [comment]
According to https://github.com/l0rdn1kk0n/wicket-jquery-selectors/commits/master I have released 0.1.6 & 0.2.3 after the upgrade to Jackson 2.6 for this problem.
If you still face this problem with any of these versions then there must be another problem.

**Comment by danjee** [comment]
I will review the version later this day, most likely I have an older version on my project.

**Comment by danjee** [comment]
You were right, some older version of Jackson was in my classpath.
